// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNHmIfGer_0DEsZ4N1gPZX3VVAGPAZH5A',
    appId: '1:713995172811:web:81737e86737b0695ab944e',
    messagingSenderId: '713995172811',
    projectId: 'mynotes-lokesh-project',
    authDomain: 'mynotes-lokesh-project.firebaseapp.com',
    storageBucket: 'mynotes-lokesh-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj9hQgyONl0dMJIfA7_BsCLh0LbSF3FgI',
    appId: '1:713995172811:android:2ff304245ab9626fab944e',
    messagingSenderId: '713995172811',
    projectId: 'mynotes-lokesh-project',
    storageBucket: 'mynotes-lokesh-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLG0U2TDcNL6j1kXbmH9emm5oxUzIlWkY',
    appId: '1:713995172811:ios:a347bc2bb0347587ab944e',
    messagingSenderId: '713995172811',
    projectId: 'mynotes-lokesh-project',
    storageBucket: 'mynotes-lokesh-project.appspot.com',
    iosClientId: '713995172811-6com918vq09flutgn669vpqbce1itcjb.apps.googleusercontent.com',
    iosBundleId: 'com.newapp.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLG0U2TDcNL6j1kXbmH9emm5oxUzIlWkY',
    appId: '1:713995172811:ios:a347bc2bb0347587ab944e',
    messagingSenderId: '713995172811',
    projectId: 'mynotes-lokesh-project',
    storageBucket: 'mynotes-lokesh-project.appspot.com',
    iosClientId: '713995172811-6com918vq09flutgn669vpqbce1itcjb.apps.googleusercontent.com',
    iosBundleId: 'com.newapp.mynotes',
  );
}
